export type CatalogItem = {
  id: string
  title: string
  category: string
  company_name: string
  price_from: number | null
  price_to: number | null
  description: string
  tags: string[]
  isPiqton?: boolean
  isAd?: boolean
  url?: string
  contact_url?: string
  og_image_url?: string
  display_start_date?: string | null
  display_end_date?: string | null
}

export const CATEGORIES = [
  'すべて',
  'ワークショップ',
  'ステージ・演出',
  '音響・映像',
  'アトラクション',
  'フード・飲食',
  'キャラクター・コスプレ',
  '展示・ブース',
  'その他',
] as const

const BASE = 'https://workshop.picoton.com'

// ピコトン ワークショップ商品（https://workshop.picoton.com/）
// 価格は100名参加時の目安です。実際の金額はお問い合わせください。
export const CATALOG: CatalogItem[] = [
  // ── 基本キット（道具付属なし）14点 ──
  {
    id: 'pq-ws-01',
    title: '光る！ウォータースティックライト',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 50000,
    price_to: null,
    description: '水を入れると光るオリジナルスティックライトを作るワークショップ。対象年齢3歳〜、所要時間15〜25分。',
    tags: ['光る', '工作', '幼児向け', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/waterstick/thumbnail.webp`,
  },
  {
    id: 'pq-ws-02',
    title: 'ピカッと！安全キーホルダー',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 50000,
    price_to: null,
    description: '夜道を明るく照らす反射材入りキーホルダーを手作りするワークショップ。交通安全教育にも最適。対象年齢3歳〜、所要時間15〜25分。',
    tags: ['安全', 'キーホルダー', '反射材', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/reflector/thumbnail.webp`,
  },
  {
    id: 'pq-ws-03',
    title: 'Myおうちバッグ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 60000,
    price_to: null,
    description: 'おうちの形をしたバッグにオリジナルデザインを描いて作るワークショップ。対象年齢3歳〜、所要時間30〜45分。',
    tags: ['バッグ', '工作', 'デザイン', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/home_bag/thumbnail.webp`,
  },
  {
    id: 'pq-ws-04',
    title: 'エッグマラカス',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 55000,
    price_to: null,
    description: '卵型のマラカスをデコレーションして作るワークショップ。音楽イベントや子ども向けフェスに好評。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['音楽', 'マラカス', '工作', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/egg/thumbnail.webp`,
  },
  {
    id: 'pq-ws-05',
    title: 'キッズエコバッグ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 55000,
    price_to: null,
    description: 'SDGs・環境教育テーマのエコバッグを手作りするワークショップ。環境意識を楽しく育てます。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['SDGs', 'エコ', 'バッグ', '環境', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/ecobag/thumbnail.webp`,
  },
  {
    id: 'pq-ws-06',
    title: '光る！デコうちわ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 50000,
    price_to: null,
    description: '光る素材でデコレーションした夏にぴったりのうちわを作るワークショップ。対象年齢3歳〜、所要時間15〜25分。',
    tags: ['光る', 'うちわ', '夏', '季節', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/decouchiwa/thumbnail.webp`,
  },
  {
    id: 'pq-ws-07',
    title: '地層ジオラマ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 55000,
    price_to: null,
    description: '砂や土で地球の地層を再現するジオラマ工作ワークショップ。理科・科学教育にも活用できます。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['理科', 'ジオラマ', '地層', 'STEM', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/strata-diorama/thumbnail.webp`,
  },
  {
    id: 'pq-ws-08',
    title: '歩く！ゼンマイロボ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 60000,
    price_to: null,
    description: 'ゼンマイ仕掛けで実際に歩くロボットを組み立てるワークショップ。ものづくりとSTEAM教育に。対象年齢3歳〜、所要時間30〜45分。',
    tags: ['ロボット', '工作', 'STEM', '動く', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/zenmai_robo/thumbnail.webp`,
  },
  {
    id: 'pq-ws-09',
    title: 'ハロウィンマスク',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 55000,
    price_to: null,
    description: 'ハロウィンテーマのオリジナルマスクを作るワークショップ。秋のイベントに最適。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['ハロウィン', 'マスク', '秋', '季節', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/mask/thumbnail2.webp`,
  },
  {
    id: 'pq-ws-10',
    title: '走る！フリクション電車',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 60000,
    price_to: null,
    description: '摩擦力で走るオリジナル電車を作るワークショップ。電車好きのお子さまに大人気。対象年齢3歳〜、所要時間30〜45分。',
    tags: ['電車', '工作', 'STEM', '動く', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/friction_train/thumbnail.webp`,
  },
  {
    id: 'pq-ws-11',
    title: 'クリスタル万華鏡',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 50000,
    price_to: null,
    description: 'クリスタルと鏡を使ってオリジナル万華鏡を作るワークショップ。光と色の不思議を体験。対象年齢3歳〜、所要時間15〜25分。',
    tags: ['万華鏡', '光学', '工作', 'サイエンス', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/kaleidoscope/thumbnail.webp`,
  },
  {
    id: 'pq-ws-12',
    title: '色が変わる不思議コマ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 55000,
    price_to: null,
    description: '回すと色が変化する不思議なコマを作るワークショップ。色彩の科学を楽しく体験できます。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['コマ', '色彩', 'サイエンス', '不思議', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/spinning-top/thumbnail.webp`,
  },
  {
    id: 'pq-ws-13',
    title: 'リサイクル・フラワーベース',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 55000,
    price_to: null,
    description: 'リサイクル素材を使ったフラワーベース（花瓶）作りのワークショップ。SDGs・環境教育にぴったり。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['SDGs', 'リサイクル', '環境', 'フラワー', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/flowervase/thumbnail.webp`,
  },
  {
    id: 'pq-ws-14',
    title: '走る！デザインカー',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 55000,
    price_to: null,
    description: 'オリジナルデザインで走るミニカーを作るワークショップ。デザインとものづくりを同時に楽しめます。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['車', '工作', 'デザイン', '動く', '基本キット'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/design-car/thumbnail.webp`,
  },
  // ── ツール付きセット（プレミアム）8点 ──
  {
    id: 'pq-ws-15',
    title: 'うごく！シャッフルぬりえ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 80000,
    price_to: null,
    description: '3,000種以上のデザインからぬりえが選べるインタラクティブ体験型ワークショップ。デジタルと手作りを融合。対象年齢3歳〜、所要時間15〜25分。',
    tags: ['デジタル', 'ぬりえ', 'インタラクティブ', 'プレミアム'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/shufflenurie_move/thumbnail.webp`,
  },
  {
    id: 'pq-ws-16',
    title: '飛べ！おりがみヒコーキ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 70000,
    price_to: null,
    description: '日本折り紙ヒコーキ協会認定の折り紙飛行機を作るワークショップ。よく飛ぶ本格的な紙飛行機に挑戦。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['折り紙', 'ヒコーキ', '認定', 'プレミアム'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/origami/thumbnail.webp`,
  },
  {
    id: 'pq-ws-17',
    title: 'グラスガーデン',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 80000,
    price_to: null,
    description: 'ガラス容器に砂や小石・ミニチュアを詰めてミニテラリウムを作るワークショップ。繊細で可愛い作品が完成。対象年齢3歳〜、所要時間15〜25分。',
    tags: ['テラリウム', '植物', 'ガーデン', 'プレミアム'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/glassgarden/thumbnail2.webp`,
  },
  {
    id: 'pq-ws-18',
    title: 'アートパネル',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 80000,
    price_to: null,
    description: 'プロ仕様のキャンバスパネルに絵を描くアートワークショップ。本格的な画材を使って世界に一つの作品を。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['アート', 'キャンバス', '絵画', 'プレミアム'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/artpanel/thumbnail.webp`,
  },
  {
    id: 'pq-ws-19',
    title: 'つくってタオル',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 90000,
    price_to: null,
    description: 'オリジナルデザインをプリントしたタオルを作るワークショップ。実用的でプレゼントにもなる記念品が完成。対象年齢3歳〜、所要時間30〜45分。',
    tags: ['タオル', 'プリント', 'オリジナル', 'プレミアム'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/arttowel/thumbnail.webp`,
  },
  {
    id: 'pq-ws-20',
    title: '光る！星座ボックス',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 80000,
    price_to: null,
    description: '暗くすると星座が浮かび上がる光る箱を作るワークショップ。宇宙・天文テーマのイベントに最適。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['星座', '光る', '宇宙', 'プレミアム'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/seizabox/thumbnail2.webp`,
  },
  {
    id: 'pq-ws-21',
    title: '化石コースター',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 80000,
    price_to: null,
    description: '石素材に化石模様を刻んだコースターを作るワークショップ。恐竜・自然テーマのイベントで大好評。対象年齢3歳〜、所要時間20〜35分。',
    tags: ['化石', '石', '理科', '恐竜', 'プレミアム'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/fossil/thumbnail.webp`,
  },
  {
    id: 'pq-ws-22',
    title: '発見！デカマップ',
    category: 'ワークショップ',
    company_name: 'ピコトン',
    price_from: 90000,
    price_to: null,
    description: '大きな地図を使って地域の発見や謎解きを楽しむゲーム型ワークショップ。地域学習・まちあるきイベントにも。対象年齢6歳〜、所要時間30〜40分。',
    tags: ['地図', '地域', 'ゲーム', '謎解き', 'プレミアム'],
    isPiqton: true,
    contact_url: 'https://workshop.picoton.com/',
    og_image_url: `${BASE}/image/event/dekamap/thumbnail.webp`,
  },
]
